# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-20 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S',
        ),
    ]
