# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_wiki_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default=1, max_length=128, verbose_name='桶名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default=1, max_length=32, verbose_name='桶区域'),
            preserve_default=False,
        ),
    ]
